name: schedule

on:
  push:
  pull_request:
    branches: [main gh-pages]
  schedule:
    #   分 时 日 月 周
    - cron: "* */12 * * *"
  repository_dispatch:
    types:
      - update_app
  workflow_dispatch:
#   fork:
#     branches: [main gh-pages]
#   label:
#     types:
#       - created
#   issues:
#     types:
#       - opened
#       - labeled
#   page_build:
#     branches: [main gh-pages]
#   workflow_run:
#     workflows: ["Build"]
#     types: [requested]
#     # branches-ignore:
#     #   - "canary"
#   workflow_dispatch:
#     inputs:
#       logLevel:
#         description: "Log level"
#         required: true
#         default: "warning"
#         type: choice
#         options:
#           - info
#           - warning
#           - debug
#       print_tags:
#         description: "True to print to STDOUT"
#         required: true
#         type: boolean
#       tags:
#         description: "Test scenario tags"
#         required: true
#         type: string
#       environment:
#         description: "Environment to run tests against"
#         type: environment
#         required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'GitHubAction')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
        # https://docs.github.com/cn/actions/learn-github-actions/environment-variables
        env:
          GITHUB_TOKEN: "${{ secrets.GTOKEN }}"
          GITHUB_TOKEN1: "${{ secrets.GTOKEN }}"

      - name: setup_1->Build_with_Maven
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/NetCapture/JHook.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            ls
            chmod -R 777 *
            cd JHook
            git config core.filemode false
            cp android.csv ../android.csv
            cp base_req.txt ../base_req.txt
            cp ip2region.xdb ../ip2region.xdb
            cp libcryptbox.so ../libcryptbox.so
            ./mvnw compile assembly:single

            if [ $# == 0 ]; then
              echo "编译成功。。。。。"
              ls
              mv `ls target/*.jar` ../ts.jar
              echo "拷贝成功。。。。。"
              ls ../
            fi
          fi

      - name: setup_2-->look
        shell: bash
        continue-on-error: true
        run: ls

      - name: setup_3-->run_java_project
        shell: bash
        continue-on-error: true
        run: java -Xms2g  -Xmx2g  -Xmn1g  -XX:MetaspaceSize=256m  -XX:MaxMetaspaceSize=256m  -XX:MaxDirectMemorySize=1g -Dfile.encoding=UTF-8 -jar  ./ts.jar   "${{ secrets.GTOKEN }}"

      - name: setup_4-->ls
        shell: bash
        continue-on-error: true
        run: ls

      # - name: setup_5-->Send_mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     #          server_address: smtp.163.com
      #     #          server_port: 465
      #     #          server_address: smtp.gmail.com
      #     #          server_port: 465
      #     server_address: smtp.exmail.qq.com
      #     server_port: 465
      #     username: ${{ secrets.MAILUSERNAME }}
      #     password: ${{ secrets.MAILPASSWORD }}
      #     subject: "fq subscribe"
      #     to: ${{ secrets.MAIL_LIST }}
      #     from: GithubActions
      #     secure: true
      #     # Optional unsigned/invalid certificates allowance:
      #     ignore_cert: true
      #     #  body:  |
      #     #    Build job ( ${{ github.job }} ) of ${{ github.repository }} completed successfully!
      #     #    Commit msg: ${{ github.event.head_commit.message }}
      #     # html_body: file://vy.txt
      #     # body:  #Build job of ${{github.repository}} completed successfully!
      #     body:  Build job completed successfully!
      #     attachments:  vy.txt
      #     priority: high

