name: schedule-update
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # run every 1 hour
  schedule:
    #   分 时 日 月 周
    - cron: '*/1 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/NetCapture/JHook.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            ls
            chmod -R 777 *
            cd JHook
            git config core.filemode false
            ./mvnw compile assembly:single
            
            if [ $# == 0 ]; then
              echo "编译成功。。。。。"
              ls
              mv `ls target/*.jar` ../ts.jar
              echo "拷贝成功。。。。。"
              ls ../
            fi
          fi
          
      - name: run java project
        run: java -jar  ./ts.jar

